# Generated by Django 5.1.6 on 2025-02-20 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_taskgroup_task_taskgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_detail', to='home.taskgroup'),
        ),
    ]
